# Generated by Django 4.2.7 on 2023-11-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('label', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Label',
        ),
    ]
